##Описание ошибки
В тот момент, когда только начинает выполняться первый ```callback```, цикл уже закончился и перeменная  ```request ``` содержит последний  элемент массива ```requests```, равный '/populations'. Т.е. у всех 3х  ```callback ```'ов  ```result ``` запишется в одну и ту же ячейку  ```responses['/populations'] ```. затем длина массива ```l``` при всех 3х выполнениях  ```callback ```'а будет равна 1 и  ```if (l.length == 3) ``` ни разу не выполнится.
##Решение
Решить данную проблему можно, обернув ```callback``` в функцию, которую я обозвал ```sendRequest```. Затем в цикле вызываем эту функцию и передаем параметром элемент массива ```requests[i]```.
##Как избежать подобной ошибки
Подобная ошибка могла возникнуть из-за непонимания принципов устройства пространства имен в JavaScript. Необходимо следить за областью видимости перемнных.
##Диалог с пользователем
[Мой пример](http://urkass.github.io/API-Yandex/)
